version: '3.1'
services:
  redis:
    image: "redis:alpine"
    container_name: order_redis
    command: redis-server --loglevel warning --save 60 1
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master