/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecom.schema.product;
@org.apache.avro.specific.AvroGenerated
public enum ProductStatusEnum implements org.apache.avro.generic.GenericEnumSymbol<ProductStatusEnum> {
  CREATED, UPDATED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductStatusEnum\",\"namespace\":\"com.ecom.schema.product\",\"symbols\":[\"CREATED\",\"UPDATED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}