spring:
  profiles:
    active: local
  application:
    name: 'payment-management-service'

server:
  port: 8100

logging:
  level:
    root: INFO
    com:
      ecom: DEBUG
---
spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
spring:
  config:
    activate:
      on-profile:
        - non-prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
spring:
  config:
    activate:
      on-profile:
        - prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
